# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-25 22:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relatedyears',
            name='year',
            field=models.CharField(max_length=11),
        ),
    ]
