# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-23 02:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_1', models.CharField(max_length=128, verbose_name='address')),
                ('address_2', models.CharField(blank=True, max_length=128, verbose_name="address cont'd")),
                ('city', models.CharField(default='Brooklyn', max_length=64, verbose_name='city')),
                ('state', models.CharField(default='NY', max_length=2, verbose_name='state')),
                ('zip_code', models.CharField(default='11216', max_length=5, verbose_name='zip code')),
            ],
        ),
        migrations.AddField(
            model_name='location',
            name='address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='interviews.Address'),
        ),
    ]
