# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-23 02:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0002_auto_20160923_0248'),
    ]

    operations = [
        migrations.CreateModel(
            name='Neighborhoods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=128)),
            ],
        ),
        migrations.AlterField(
            model_name='location',
            name='images',
            field=models.ManyToManyField(blank=True, null=True, to='interviews.Images'),
        ),
        migrations.RemoveField(
            model_name='location',
            name='neighborhood',
        ),
        migrations.AlterField(
            model_name='person',
            name='event',
            field=models.ManyToManyField(blank=True, null=True, to='interviews.Event'),
        ),
        migrations.AddField(
            model_name='location',
            name='neighborhood',
            field=models.ManyToManyField(blank=True, null=True, to='interviews.Neighborhoods'),
        ),
    ]
