# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-24 01:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0003_auto_20160923_0255'),
    ]

    operations = [
        migrations.CreateModel(
            name='RelatedStages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='RelatedThings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thing', models.CharField(max_length=200)),
            ],
        ),
        migrations.RenameField(
            model_name='event',
            old_name='title',
            new_name='extract',
        ),
        migrations.RenameField(
            model_name='images',
            old_name='name',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='neighborhoods',
            old_name='type',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='themes',
            old_name='name',
            new_name='theme',
        ),
        migrations.AddField(
            model_name='person',
            name='color',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='images',
            field=models.ManyToManyField(blank=True, to='interviews.Images'),
        ),
        migrations.AlterField(
            model_name='event',
            name='location',
            field=models.ManyToManyField(blank=True, to='interviews.Location'),
        ),
        migrations.AlterField(
            model_name='event',
            name='themes',
            field=models.ManyToManyField(blank=True, to='interviews.Themes'),
        ),
        migrations.AlterField(
            model_name='location',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='interviews.Address'),
        ),
        migrations.AlterField(
            model_name='location',
            name='images',
            field=models.ManyToManyField(blank=True, to='interviews.Images'),
        ),
        migrations.AlterField(
            model_name='location',
            name='related_people',
            field=models.ManyToManyField(to='interviews.RelatedPeople'),
        ),
        migrations.AlterField(
            model_name='person',
            name='event',
            field=models.ManyToManyField(blank=True, to='interviews.Event'),
        ),
        migrations.AddField(
            model_name='event',
            name='stage',
            field=models.ManyToManyField(blank=True, to='interviews.RelatedStages'),
        ),
        migrations.AddField(
            model_name='event',
            name='things',
            field=models.ManyToManyField(blank=True, to='interviews.RelatedThings'),
        ),
    ]
