# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-24 01:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0004_auto_20160924_0105'),
    ]

    operations = [
        migrations.CreateModel(
            name='RelatedYears',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(max_length=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='event',
            name='year',
        ),
        migrations.AddField(
            model_name='event',
            name='years',
            field=models.ManyToManyField(blank=True, to='interviews.RelatedYears'),
        ),
    ]
