# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-06-14 02:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0004_auto_20160925_2326'),
    ]

    operations = [
        migrations.CreateModel(
            name='Excerpt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extract', models.CharField(max_length=2000)),
                ('beginning_time', models.IntegerField(blank=True, null=True)),
                ('duration', models.IntegerField(blank=True, null=True)),
                ('images', models.ManyToManyField(blank=True, to='interviews.Images')),
                ('themes', models.ManyToManyField(blank=True, to='interviews.Themes')),
            ],
        ),
        migrations.RenameModel(
            old_name='Person',
            new_name='Women',
        ),
        migrations.RemoveField(
            model_name='event',
            name='images',
        ),
        migrations.RemoveField(
            model_name='event',
            name='location',
        ),
        migrations.RemoveField(
            model_name='event',
            name='people',
        ),
        migrations.RemoveField(
            model_name='event',
            name='stage',
        ),
        migrations.RemoveField(
            model_name='event',
            name='themes',
        ),
        migrations.RemoveField(
            model_name='event',
            name='things',
        ),
        migrations.RemoveField(
            model_name='event',
            name='years',
        ),
        migrations.RemoveField(
            model_name='location',
            name='address',
        ),
        migrations.RemoveField(
            model_name='location',
            name='images',
        ),
        migrations.RemoveField(
            model_name='location',
            name='map_features',
        ),
        migrations.RemoveField(
            model_name='location',
            name='neighborhood',
        ),
        migrations.RemoveField(
            model_name='location',
            name='place_category',
        ),
        migrations.RemoveField(
            model_name='women',
            name='event',
        ),
        migrations.DeleteModel(
            name='Address',
        ),
        migrations.DeleteModel(
            name='Event',
        ),
        migrations.DeleteModel(
            name='Location',
        ),
        migrations.DeleteModel(
            name='MapFeatures',
        ),
        migrations.DeleteModel(
            name='Neighborhoods',
        ),
        migrations.DeleteModel(
            name='RelatedPeople',
        ),
        migrations.DeleteModel(
            name='RelatedStages',
        ),
        migrations.DeleteModel(
            name='RelatedThings',
        ),
        migrations.DeleteModel(
            name='RelatedYears',
        ),
        migrations.AddField(
            model_name='women',
            name='excerpt',
            field=models.ManyToManyField(blank=True, to='interviews.Excerpt'),
        ),
    ]
