# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-06-14 02:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0005_auto_20170614_0204'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='women',
            name='color',
        ),
    ]
