# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-24 01:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0005_auto_20160924_0109'),
    ]

    operations = [
        migrations.CreateModel(
            name='MapFeature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature', models.CharField(max_length=128)),
            ],
        ),
        migrations.RemoveField(
            model_name='location',
            name='related_people',
        ),
        migrations.AddField(
            model_name='event',
            name='related_people',
            field=models.ManyToManyField(to='interviews.RelatedPeople'),
        ),
        migrations.AddField(
            model_name='location',
            name='map_feature',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='interviews.MapFeature'),
        ),
    ]
