# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-24 01:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0006_auto_20160924_0119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='related_people',
            field=models.ManyToManyField(blank=True, to='interviews.RelatedPeople'),
        ),
        migrations.AlterField(
            model_name='relatedyears',
            name='year',
            field=models.CharField(max_length=10),
        ),
    ]
