# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-24 01:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0007_auto_20160924_0125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
