# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-24 01:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0008_auto_20160924_0126'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='related_people',
            new_name='people',
        ),
    ]
